import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Dosis } from 'next/font/google';
import './globals.css';

const dosis = Dosis({
  variable: '--font-dosis',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.variable} font-[family-name:var(--font-dosis)] antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
