import { getBrands } from '@/api/brand';
import { getPerfumeCollections } from '@/api/perfumeCollections';
import { getFulfilledResponse } from '@/api/utils';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Provider from '@/components/Provider';
import type { Metadata } from 'next';
import { Dosis } from 'next/font/google';
import './globals.css';

const dosis = Dosis({
  variable: '--font-dosis',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [_brand, _perfumeCollections] = await Promise.allSettled([getBrands(), getPerfumeCollections()]);
  const brands = getFulfilledResponse(_brand);
  const perfumeCollections = getFulfilledResponse(_perfumeCollections);
  return (
    <html
      lang="en"
      className="mdl-js"
    >
      <body className={`${dosis.variable} font-[family-name:var(--font-dosis)] antialiased`}>
        <Provider>
          {' '}
          <Header
            brands={brands?.responseData?.data ?? []}
            perfumeCollections={perfumeCollections?.responseData?.data ?? []}
          />
          {children}
          <Footer perfumeCollections={perfumeCollections?.responseData?.data ?? []} />
        </Provider>
      </body>
    </html>
  );
}
